name = "reminder-bot"
main = "src/index.ts"
compatibility_date = "2025-03-25"

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "reminder-bot-db"
database_id = "f8bbbf30-33fc-4da9-8d93-b7bd4b545713"
migrations_dir = "migrations"

[vars]
TIMEZONE = "Asia/Shanghai"
