name = "reminder-bot"
main = "src/index.ts"
compatibility_date = "2025-03-25"

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["*/30 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "reminder-bot-db"
database_id = "e8ea3d78-62a5-4fd6-95e3-5f41a7596d0f"

[vars]
TIMEZONE = "Asia/Shanghai"
